// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBK9AuFFrl-qI_veHLlZ6tOXE0DLLqc8wM',
    appId: '1:835433669788:web:2781994c639419b4b6f959',
    messagingSenderId: '835433669788',
    projectId: 'loginauth-b9a06',
    authDomain: 'loginauth-b9a06.firebaseapp.com',
    storageBucket: 'loginauth-b9a06.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLXj2tGArp0ufwJuPDoJzG_tcv2lbp0dY',
    appId: '1:835433669788:android:4e0f584048d0021db6f959',
    messagingSenderId: '835433669788',
    projectId: 'loginauth-b9a06',
    storageBucket: 'loginauth-b9a06.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAY-IwWN4V0B_mukwgU7vceMLop6EIMjig',
    appId: '1:835433669788:ios:772cb55f811640fab6f959',
    messagingSenderId: '835433669788',
    projectId: 'loginauth-b9a06',
    storageBucket: 'loginauth-b9a06.firebasestorage.app',
    androidClientId: '835433669788-4ta22jht42uuh9cbp5gpdee2u5j5cj8d.apps.googleusercontent.com',
    iosClientId: '835433669788-imhesoie181p8a7li8fhq17mp0cngeho.apps.googleusercontent.com',
    iosBundleId: 'com.example.tutorialapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAY-IwWN4V0B_mukwgU7vceMLop6EIMjig',
    appId: '1:835433669788:ios:772cb55f811640fab6f959',
    messagingSenderId: '835433669788',
    projectId: 'loginauth-b9a06',
    storageBucket: 'loginauth-b9a06.firebasestorage.app',
    androidClientId: '835433669788-4ta22jht42uuh9cbp5gpdee2u5j5cj8d.apps.googleusercontent.com',
    iosClientId: '835433669788-imhesoie181p8a7li8fhq17mp0cngeho.apps.googleusercontent.com',
    iosBundleId: 'com.example.tutorialapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBK9AuFFrl-qI_veHLlZ6tOXE0DLLqc8wM',
    appId: '1:835433669788:web:d2ad623e2452571ab6f959',
    messagingSenderId: '835433669788',
    projectId: 'loginauth-b9a06',
    authDomain: 'loginauth-b9a06.firebaseapp.com',
    storageBucket: 'loginauth-b9a06.firebasestorage.app',
  );
}
